### ISSUE TITLE
service-manager is started twice?

### ISSUE THREAD

**Issue by dirkvdplas** [reduardo7/bash-service-manager#1]
Hi, 

I want to use bash-service-manager for controlling starting and stopping of a python script (logtooltje.py)
Starting the python script via service-manager goes fine. But it won't stop. 
I noticed that for some reason the servicemanager (named logdaemon in my example) is is started twice. When I  perform "logdaemon stop", the PID-file is removed and one logdaemon proces is killed. However there is still one logdaemon process running, including the python script.

Below the commands to visualize the issue.
Your help is much appreciated.

+++++++++++++++++
[goldeneye@server-x daemon]$ cat logdaemon
#!/usr/bin/bash

export PID_FILE_PATH="/tmp/my-service.pid"
export LOG_FILE_PATH="/tmp/my-service.log"
export LOG_ERROR_FILE_PATH="/tmp/my-service.error.log"

# Import or paste "services.sh"
. services.sh

run-logtooltje() {
python logtooltje.py
}

action="$1"
serviceName="logtooltje"
workDir="/home/plas109/flowanalysis/daemon"
command="run-logtooltje"

serviceMenu "$action" "$serviceName" "$command" "$workdir"
++++++++++++++++++++++++++++++++++++++++++++

[goldeneye@server-x daemon]$ ./logdaemon start
# Starting logtooltje service...
[goldeneye@server-x daemon]$ ps -ef | grep logda
goldeneye   6251     1  0 23:19 pts/4    00:00:00 /usr/bin/bash ./logdaemon start
goldeneye   6252  6251  0 23:19 pts/4    00:00:00 /usr/bin/bash ./logdaemon start
goldeneye   6257 22139  0 23:19 pts/4    00:00:00 grep --color=auto logda
[goldeneye@server-x daemon]$ ps -ef | grep logto
goldeneye   6253  6252  0 23:19 pts/4    00:00:00 python logtooltje.py
goldeneye   6259 22139  0 23:19 pts/4    00:00:00 grep --color=auto logto
[goldeneye@server-x daemon]$ cat /tmp/my-service.pid
6251

Now stopping the servicemanager:

[goldeneye@server-x daemon]$ ./logdaemon stop
# Stopping logtooltje...
[goldeneye@server-x daemon]$ cat /tmp/my-service.pid
cat: /tmp/my-service.pid: No such file or directory
[goldeneye@server-x daemon]$ ps -ef | grep logdaemon
goldeneye   6252     1  0 23:19 pts/4    00:00:00 /usr/bin/bash ./logdaemon start
goldeneye   6286 22139  0 23:20 pts/4    00:00:00 grep --color=auto logdaemon
[goldeneye@server-x daemon]$ ps -ef | grep logtooltje.py
goldeneye   6253  6252  0 23:19 pts/4    00:00:00 python logtooltje.py
goldeneye   6290 22139  0 23:20 pts/4    00:00:00 grep --color=auto logtooltje.py

Python script is still running

**Comment by lisbravo** [comment]
@dirkvdplas hi, Im having the same Issue, did you manage to fix it?

**Comment by dirkvdplas** [comment]
Sorry man. It's 2.5 years ago I honestly dont know if and how I fixed it.

Op vr 10 apr. 2020 11:39 schreef Lisandro Bravo <notifications@github.com>:

**Comment by artemiuss** [comment]
try my fork https://github.com/artemiuss/bash-service-manager

**Comment by reduardo7** [comment]
> try my fork https://github.com/artemiuss/bash-service-manager

Thank you! Can you make a Pull Request to integrate it?
